# Generated by Django 3.2.7 on 2021-09-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_phone_number_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone_number',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
